Sprint 04
Larexander/MovieQuiz-ios pull request #1
Opened 2022-12-11 06:24 UTC by Larexander

2022-12-11 10:10 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let action = UIAlertAction(title: result.buttonText, style: .default) {_ in
после фигурной скобки в данном случае нужен пробел
```suggestion
        let action = UIAlertAction(title: result.buttonText, style: .default) { _ in
```

2022-12-11 10:12 UTC, ABashkirova requested changes

2022-12-11 10:12 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.borderColor = isCorrect ? UIColor.green.cgColor : UIColor.red.cgColor
masksToBounds, cornerRadius  – настройки, которые можно сделать один раз на сториборде или во viewDidLoad

2022-12-11 10:12 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self.yesButton.isEnabled = true
🙌

2022-12-11 10:12 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.borderColor = isCorrect ? UIColor.green.cgColor : UIColor.red.cgColor
Для цвета из ассетов есть инициализатор UIColor(named: ..)

2022-12-11 13:44 UTC, ABashkirova commented on MovieQuiz/Presentation/Base.lproj/Main.storyboard
> +                            <stackView opaque="NO" contentMode="scaleToFill" axis="vertical" spacing="8" translatesAutoresizingMaskIntoConstraints="NO" id="G6s-8d-rLk" userLabel="Main Stcak">
по дизайну spacing 20

2022-12-11 13:47 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.borderColor = isCorrect ? UIColor(named: "YP Green (iOS)")!.cgColor : UIColor(named: "YP Red (iOS)")!.cgColor
Я не рекомендую использовать focreunwrapping в учебном коде (даже если это работает), это не самая лучшая черта работ будущего джуна
```suggestion
        imageView.layer.borderColor = isCorrect ? UIColor(named: "YP Green (iOS)")?.cgColor : UIColor(named: "YP Red (iOS)")?.cgColor
```

однако как константу (в расширение Colors в helper), можешь вынести статическим свойством с force unwrap'ом – для констант это в целом приемлемо

2022-12-11 13:48 UTC, ABashkirova commented on MovieQuiz/Resources/Info.plist
> +                 <string>YS Display-Thin</string>
лучше оставить только необходимые

2022-12-11 14:22 UTC, merged

2022-12-12 05:38 UTC, Larexander commented
The fourth sprint has been successfully completed